# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 21565be9dbcf3ada98687adbfcf61e4fef285f21e9e5ab45c13655b47c360508c742ef1ed65ff3c09bba607c1125516e17521c88056f10dd7075be12c867db60

test:
  secret_key_base: e24c056346cadd27f29fdaa165b0174e77253f7b060687cb5f3c7b8050ebc44af42c4209b5bc58748f65ff305ed5089d521df0594c26f8225d180a1993f69f34

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
